#!/usr/bin/env python3
"""Strip trailing whitespace from the lines a pull request added.

Only the "+" lines of ``git diff BASE_TIP...HEAD`` are touched. Lines the pull
request did not write keep their bytes even in files it modified, so the
cleanup never produces an unrelated hunk. A renamed file counts as the lines it
changed, the same way git reports it, and not as a file added whole.

The rule set mirrors .editorconfig, which lives on indev. This script runs from
main, where that file does not exist yet, so the rules are repeated here and
have to be kept in step with it:

    *.md                      left alone, two trailing spaces are a hard break
    baseline/                 generated by bootstrap, trim_trailing_whitespace
    VintagestoryApi/          is off for all of them because extract-patches
    Cairo/                    diffs these trees against the pristine baseline
    VSCreativeMod/
    VSEssentials/
    VSSurvivalMod/
    *.patch                   only the diff's own added lines, see below
    everything else           stripped

A .patch file is a unified diff that has to keep applying. Among the lines the
pull request added to it, only those starting with "+" are the patch's own
added content; a "+++" line is a header. Context (" "), removed ("-"), "@@",
"diff", "index" and "---" lines must stay byte identical to the vanilla
baseline or the patch stops applying, and none of them start with "+", so the
single "+" and not "+++" test covers the whole rule.

Spaces and tabs before the line ending go; a CRLF ending stays CRLF, which is
what .ps1 files use per .gitattributes.

Environment:
    BASE_TIP       commit to diff HEAD against
    STRIP_MESSAGE  optional file to write the commit message into
    STRIP_PATHS    optional file to write the rewritten paths into, NUL
                   separated, for the caller to stage exactly those

Prints "<files> <lines>" on stdout. Runs git and nothing else: no file from the
checked out tree is executed or imported.
"""

import os
import re
import subprocess
import sys

EXCLUDED_PREFIXES = (
    "baseline/",
    "VintagestoryApi/",
    "Cairo/",
    "VSCreativeMod/",
    "VSEssentials/",
    "VSSurvivalMod/",
)

# @@ -<old> +<start>[,<count>] @@ ; with -U0 every line of the new side that a
# hunk covers is a line the pull request added or rewrote.
HUNK = re.compile(rb"^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@")


def git(*args):
    return subprocess.run(
        ("git",) + args, check=True, stdout=subprocess.PIPE
    ).stdout


def changed_files(base):
    """Yield (path, pathspec) for every file the pull request touched.

    A rename is reported as one entry carrying the old and the new path, and
    both of them have to go into the pathspec below. Pathspec filtering runs
    before rename detection, so asking for the new path alone leaves the old
    one out of the diff queue, git calls the file brand new and reports every
    line of it as added: a pure rename would have its whole content rewritten.
    """
    out = git(
        "diff", "--name-status", "-z", "-M", "--diff-filter=ACMR",
        base + "...HEAD",
    )
    fields = [f for f in out.split(b"\0") if f]
    i = 0
    while i < len(fields):
        status = fields[i]
        if status[:1] in (b"R", b"C"):
            old, new = fields[i + 1], fields[i + 2]
            i += 3
            yield os.fsdecode(new), [os.fsdecode(old), os.fsdecode(new)]
        else:
            new = fields[i + 1]
            i += 2
            yield os.fsdecode(new), [os.fsdecode(new)]


def added_line_numbers(base, pathspec):
    # ":(literal)" so a path with a glob character is not read as a pathspec.
    out = git(
        "diff", "-U0", "-M", base + "...HEAD", "--",
        *(":(literal)" + p for p in pathspec)
    )
    numbers = set()
    for line in out.split(b"\n"):
        match = HUNK.match(line)
        if not match:
            continue
        start = int(match.group(1))
        count = 1 if match.group(2) is None else int(match.group(2))
        numbers.update(range(start, start + count))
    return numbers


def strip_eol(line):
    """Drop spaces and tabs before the line ending. ``line`` carries no "\\n"."""
    if line.endswith(b"\r"):
        return line[:-1].rstrip(b" \t") + b"\r"
    return line.rstrip(b" \t")


def editable_in_patch(line):
    return line.startswith(b"+") and not line.startswith(b"+++")


def main():
    base = os.environ["BASE_TIP"]
    changed = []

    for path, pathspec in changed_files(base):
        if path.endswith(".md") or path.startswith(EXCLUDED_PREFIXES):
            continue
        # A symlink in the tree would send the rewrite outside the repository.
        if os.path.islink(path) or not os.path.isfile(path):
            continue

        numbers = added_line_numbers(base, pathspec)
        if not numbers:
            continue

        is_patch = path.endswith(".patch")
        with open(path, "rb") as handle:
            content = handle.read()
        # git only calls a blob binary when a NUL byte sits in its first 8000
        # bytes, so a file that turns binary later than that arrives here with
        # real hunks. Rewriting its bytes would corrupt it.
        if b"\0" in content:
            continue
        parts = content.split(b"\n")

        count = 0
        for number in numbers:
            if number > len(parts):
                continue
            line = parts[number - 1]
            if is_patch and not editable_in_patch(line):
                continue
            stripped = strip_eol(line)
            if stripped != line:
                parts[number - 1] = stripped
                count += 1

        if count:
            with open(path, "wb") as handle:
                handle.write(b"\n".join(parts))
            changed.append((path, count))

    total = sum(count for _, count in changed)
    paths_path = os.environ.get("STRIP_PATHS")
    if changed and paths_path:
        with open(paths_path, "wb") as handle:
            handle.write(b"".join(os.fsencode(p) + b"\0" for p, _ in changed))

    message_path = os.environ.get("STRIP_MESSAGE")
    if changed and message_path:
        body = [
            "Strip trailing whitespace from added lines",
            "",
            "Applied by the /rebase command to the lines this pull request",
            "added. Markdown, the generated trees, and the context and removed",
            "lines of .patch files are left alone.",
            "",
        ]
        body += ["%s: %d line(s)" % (path, n) for path, n in sorted(changed)]
        # A path is bytes to git, so os.fsdecode above may have produced
        # lone surrogates; plain utf-8 would raise on them and kill the run.
        with open(
            message_path, "w", encoding="utf-8", errors="surrogateescape"
        ) as handle:
            handle.write("\n".join(body) + "\n")

    sys.stdout.write("%d %d\n" % (len(changed), total))


if __name__ == "__main__":
    main()
